steps:
  # Get current timestamp for build metadata
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo $(date -u +%Y-%m-%dT%H:%M:%SZ) > /workspace/build_time.txt'
    id: 'get-build-time'

  # Build Docker image with metadata
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TIME=$(cat /workspace/build_time.txt)
        docker build \
          -f docker/Dockerfile \
          --build-arg GIT_SHA=$SHORT_SHA \
          --build-arg BUILD_TIME=$${BUILD_TIME} \
          --build-arg ENVIRONMENT=${_DEPLOY_ENV} \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:${_VERSION} \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:latest \
          .
    id: 'build-backend'
    waitFor: ['get-build-time']

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:${_VERSION}'
      - '--region=${_REGION}'
      - '--project=$PROJECT_ID'
    id: 'deploy-backend'
    waitFor: ['push-backend']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:${_VERSION}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:latest'

substitutions:
  _VERSION: 'latest'
  _REGION: 'europe-west3'
  _DEPLOY_ENV: 'production'
  _SERVICE_NAME: 'api'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY