steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/Dockerfile', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:latest', '.']
images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:latest'