steps:
  # Get current timestamp for build metadata
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo $(date -u +%Y-%m-%dT%H:%M:%SZ) > /workspace/build_time.txt'
    id: 'get-build-time'

  # Build Docker image with metadata
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile'
      - '--build-arg'
      - 'GIT_SHA=$SHORT_SHA'
      - '--build-arg'
      - 'BUILD_TIME=$(cat /workspace/build_time.txt)'
      - '--build-arg'
      - 'ENVIRONMENT=${_DEPLOY_ENV}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:${_VERSION}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:latest'
      - '.'
    id: 'build-backend'
    waitFor: ['get-build-time']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:${_VERSION}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/hey-sh-backend/service:latest'

substitutions:
  _VERSION: 'latest'
  _REGION: 'europe-west3'
  _DEPLOY_ENV: 'development'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY