apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hey-sh-backend
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/hey-sh-production/hey-sh-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal.default.svc.cluster.local:7233"
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-config
              key: url
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-config
              key: key
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-config
              key: jwt-secret
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      serviceAccountName: default
  traffic:
  - percent: 100
    latestRevision: true
